export const data = {
  pairs: [
    ["the bank", "வங்கி"],
    ["the restaurant", "உணவகம்"],
    ["a potato", "ஒரு உருளைக்கிழங்கு"],
    ["cow", "மாடு"],
    ["chair", "நாற்காலி"],
    ["I'm beautiful", "நான் அழகாக இருக்கிறேன்"],
    ["Dad", "அப்பா"],
    ["Mom", "அம்மா"],
    ["Rice", "அரிசி"],
    ["Banyan tree", "ஆலமரம்"],
    ["Ginger", "இஞ்சி"],
    ["sea", "கடல்"],
    ["mirror", "கண்ணாடி"],
    ["cheek", "கன்னம்"],
    ["bowl", "கிண்ணம்"],
    ["parrot", "கிளி"],
    ["wheel", "சக்கரம்"],
    ["window", "சன்னல்"],
    ["lion", "சிங்கம்"],
    ["gold", "தங்கம்"],
    ["nail", "நகம்"],
    ["fox", "நரி"],
    ["moon", "நிலா"],
    ["picture", "படம்"],
    ["kite", "பட்டம்"],
    ["spinning top ", "பம்பரம்"],
    ["mole", "மச்சம்"],
    ["drum", "மத்தளம்"],
    ["fish", "மீன்"],
    ["fan", "விசிறி"],
  ],
  langA: { code: "en", name: "English" },
  langB: { code: "ta-IN", name: "Tamil" },
};
